services:
  elections-service:
    container_name: elections-service
    build:
      context: /election/.

  results-service:
    container_name: results-service
    build:
      context: /results-service/.

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: election
      POSTGRES_PASSWORD: election
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
     - "5432:5432"
    networks:
     - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: aluta182004@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Adepa2905!
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
          - "5050:80"
    networks:
      - postgres
networks:
      postgres:
        driver: bridge

volumes:
  postgres:
  pgadmin: